import type { ScheduleItemStatus, ScheduleItemType } from "../src/lib/datetime";
import { partnerBrandLogos } from "../src/lib/partner-brand-logos";

type RichTextDocument = {
  type: "doc";
  content: Array<{ type: "paragraph"; text: string }>;
};

const doc = (...paragraphs: string[]): RichTextDocument => ({
  type: "doc",
  content: paragraphs.map((text) => ({ type: "paragraph", text })),
});

export const siteSettingsSeed = {
  id: 1,
  timezone: "Europe/Sofia",
  startDate: "2026-09-18",
  endDate: "2026-09-19",
  cityBg: "София",
  cityEn: "Sofia",
  venueNameBg: "Дом на Европа",
  venueNameEn: "House of Europe",
  venueAddressBg: "София център, ул. „Георги С. Раковски“ 124, 1000 София",
  venueAddressEn: "Sofia Centre, 124 Georgi S. Rakovski Street, 1000 Sofia",
  mapUrl:
    "https://www.google.com/maps/search/?api=1&query=124+Georgi+S+Rakovski+Sofia",
  venuePublished: true,
  contactEmail: "info@narodnichitalishta.bg",
  facebookUrl: "https://www.facebook.com/narodnichitalishta/?locale=bg_BG",
  linkedinUrl:
    "https://www.linkedin.com/company/narodni-chitalishta-foundation/",
  ngoHomeUrl: "https://narodnichitalishta.bg/",
  chitalishtaMapUrl: "https://karta.narodnichitalishta.bg/",
  grantsUrl: "https://grantove.narodnichitalishta.bg/",
  dataUrl: "http://danni.narodnichitalishta.bg",
  footerBlurbBg:
    "Фондация „Народни читалища“ е създадена през октомври 2023, за да подкрепя възраждането на българските читалища.",
  footerBlurbEn: "",
  copyrightBg: "Фондация „Народни читалища“ • 2026 • Всички права запазени",
  copyrightEn: "",
  englishPublished: true,
};

export const contentSectionSeeds = [
  {
    id: "section-hero",
    slug: "hero",
    headingBg: "Културата като катализатор за местно и регионално развитие",
    headingEn: "Culture as a Catalyst for Local and Regional Development",
    contentBg: doc(
      "От локални партньорства към по-широко европейско измерение.",
    ),
    contentEn: doc("From Local Partnerships to a Broader European Dimension."),
    sortOrder: 0,
    visible: true,
  },
  {
    id: "section-introduction",
    slug: "introduction",
    headingBg: "Въведение",
    headingEn: "Introduction",
    contentBg: doc(
      "Българските читалища навършват 170 години. Огромна мрежа от 3597 читалища, 80% от които в селските райони, която крие огромен потенциал — точно този потенциал, който „Културният компас за Европа“ на ЕС ни призовава да разгърнем: културата като двигател на сближаване, устойчивост и конкурентоспособност във всяка територия, не само в столиците. Докато българските градове подготвят своите кандидатури за Европейска столица на културата 2032, истинският въпрос е дали селските и периферните общности ще бъдат част от тази история — а именно читалищата са мястото, където тази култура се изгражда отдолу-нагоре, всеки ден. Тази конференция събира евродепутати, кметове, представители на читалища, национални и местни власти, ENCC и експерти по Европейска столица на културата, за да постави местната култура отново в центъра на териториалната амбиция на Европа. Тя е трета от поредица от шест кръгли маси по програма „Bridge Makers“ на ENCC, след срещи в Чехия и Италия.",
    ),
    contentEn: doc(
      "Bulgarian community centers are celebrating their 170th anniversary. A vast network of 3,597 community centers, 80% of which are in rural areas, holds immense potential—precisely the potential that the EU’s “Cultural Compass for Europe” calls on us to unleash: culture as a driver of cohesion, sustainability, and competitiveness in every region, not just in the capitals. While Bulgarian cities are preparing their bids for the European Capital of Culture 2032, the real question is whether rural and peripheral communities will be part of this story—and it is precisely the community centers where this culture is built from the ground up, every day. This conference brings together Members of the European Parliament, mayors, representatives of community centers, national and local authorities, the ENCC, and experts on the European Capital of Culture to put local culture back at the center of Europe’s territorial ambition. It is the third in a series of six roundtables under the ENCC’s “Bridge Makers” program, following meetings in the Czech Republic and Italy.",
    ),
    sortOrder: 10,
    visible: true,
  },
  {
    id: "section-organizers",
    slug: "organizers",
    headingBg: "За организаторите",
    headingEn: "About the Organizers",
    contentBg: doc(
      "Европейската мрежа на културните центрове (ENCC) обединява над 200 социокултурни центъра и мрежи от 39 държави в Европа и извън нея, свързвайки над 5000 културни организации с разнообразни структури, практики и публики. Мрежата насърчава диалога, обучението, сътрудничеството и застъпничеството между културни оператори, чиято дейност е насочена към социално въздействие и развитие на общностите. Мрежата е съфинансирана от програма „Творческа Европа“ на Европейския съюз.",
      "Фондация „Народни читалища“ (ФНЧ) е създадена през октомври 2023 г. с мисията да подкрепя потенциала на читалищата в България, така че всеки — независимо от възраст, пол, образование или имуществено състояние — да има място, където да твори, да се информира и да учи, а всяка селска и квартална общност да има свой дом.",
    ),
    contentEn: doc(
      "The European Network of Cultural Centers (ENCC) brings together over 200 sociocultural centers and networks from 39 countries in Europe and beyond, connecting over 5,000 cultural organizations with diverse structures, practices, and audiences. The network promotes dialogue, training, collaboration, and advocacy among cultural operators whose work is focused on social impact and community development. The network is co-funded by the European Union’s “Creative Europe” program.",
      "The “Narodni Chitalishta” Foundation (NCHF) was established in October 2023 with the mission to support the potential of community centers in Bulgaria so that everyone—regardless of age, gender, education, or financial status—has a place to create, stay informed, and learn, and so that every rural and neighborhood community has a home.",
    ),
    sortOrder: 20,
    visible: true,
  },
  {
    id: "section-funding",
    slug: "funding",
    headingBg: "Финансиране и подкрепа",
    headingEn: "Funding and Support",
    contentBg: doc(
      "Събитието се финансира от Столична община и се изпълнява по проект „Bridge Makers“ на ENCC, съфинансиран от Европейския съюз. То се реализира с домакинството и подкрепата на Бюрото за връзка на Европейския парламент в България.",
    ),
    contentEn: doc(
      "The event is funded by the Sofia Municipality and is implemented as part of the ENCC’s “Bridge Makers” project, co-funded by the European Union. It is organized with the hosting and support of the European Parliament Liaison Office in Bulgaria.",
    ),
    sortOrder: 30,
    visible: true,
  },
] as const;

export const navigationItemSeeds = [
  {
    id: "nav-home",
    labelBg: "Начало",
    labelEn: "Home",
    href: "#home",
    sortOrder: 0,
    visible: true,
  },
  {
    id: "nav-about",
    labelBg: "За събитието",
    labelEn: "About",
    href: "#about",
    sortOrder: 10,
    visible: true,
  },
  {
    id: "nav-program",
    labelBg: "Програма",
    labelEn: "Program",
    href: "#program",
    sortOrder: 20,
    visible: true,
  },
  {
    id: "nav-organizers",
    labelBg: "Организатори",
    labelEn: "Organizers",
    href: "#organizers",
    sortOrder: 30,
    visible: true,
  },
  {
    id: "nav-venue",
    labelBg: "Място",
    labelEn: "Venue",
    href: "#venue",
    sortOrder: 40,
    visible: true,
  },
] as const;

export const partnerLogoMediaSeeds = partnerBrandLogos.map((logo) => ({
  id: logo.id,
  blobUrl: logo.src,
  blobPathname: logo.blobPathname,
  mimeType: logo.mimeType,
  width: logo.width,
  height: logo.height,
  altBg: logo.altBg,
  altEn: logo.altEn,
}));

export const partnerSeeds = [
  {
    id: "partner-narodnichitalishta",
    name: "Фондация „Народни читалища“",
    mediaId: "media-partner-nc-logo",
    url: "https://narodnichitalishta.bg/",
    sortOrder: 0,
    visible: true,
  },
  {
    id: "partner-encc",
    name: "European Network of Cultural Centres (ENCC)",
    mediaId: "media-partner-encc-logo",
    url: null,
    sortOrder: 10,
    visible: true,
  },
  {
    id: "partner-sofia",
    name: "Столична община",
    mediaId: "media-partner-sofia-logo",
    url: null,
    sortOrder: 20,
    visible: true,
  },
  {
    id: "partner-european-parliament",
    name: "Бюро за връзка на Европейския парламент в България",
    mediaId: "media-partner-european-parliament-logo",
    url: null,
    sortOrder: 30,
    visible: true,
  },
] as const;

export const scheduleDaySeeds = [
  {
    id: "day-2026-09-18",
    date: "2026-09-18",
    titleBg: "Ден 1",
    titleEn: "Day 1",
    subtitleBg: null,
    subtitleEn: null,
    sortOrder: 0,
    visible: true,
  },
  {
    id: "day-2026-09-19",
    date: "2026-09-19",
    titleBg: "Ден 2",
    titleEn: "Day 2",
    subtitleBg: "Само за международните гости",
    subtitleEn: "International guests only",
    sortOrder: 10,
    visible: true,
  },
] as const;

export const schedulePanelSeeds = [
  {
    id: "panel-1-local-dialogue",
    dayId: "day-2026-09-18",
    startTime: "09:50",
    endTime: "13:00",
    titleBg: "ПАНЕЛ 1 — Диалог между местните власти и читалищата",
    titleEn: "PANEL 1 — Dialogue between Local Authorities and Community Centers",
    descriptionBg: null,
    descriptionEn: null,
    sortOrder: 10,
    visible: true,
  },
  {
    id: "panel-2-european-capital",
    dayId: "day-2026-09-18",
    startTime: "13:00",
    endTime: "15:30",
    titleBg:
      "ПАНЕЛ 2 — Ролята на читалищата в Европейската столица на културата",
    titleEn: "",
    descriptionBg: null,
    descriptionEn: null,
    sortOrder: 20,
    visible: true,
  },
  {
    id: "panel-3-regional-development",
    dayId: "day-2026-09-18",
    startTime: "15:45",
    endTime: "17:45",
    titleBg: "ПАНЕЛ 3 — Културата като фактор за местно и регионално развитие",
    titleEn: "",
    descriptionBg: null,
    descriptionEn: null,
    sortOrder: 30,
    visible: true,
  },
] as const;

export type SpeakerSeed = {
  id: string;
  nameBg: string;
  nameEn: string;
  affiliationBg: string | null;
  affiliationEn: string | null;
  status?: ScheduleItemStatus;
};

export const speakerSeeds: SpeakerSeed[] = [
  {
    id: "speaker-evtim-miloshev",
    nameBg: "Евтим Милошев",
    nameEn: "",
    affiliationBg: "Министър на културата",
    affiliationEn: null,
    status: "to_be_confirmed",
  },
  {
    id: "speaker-vasil-terziev",
    nameBg: "Васил Терзиев",
    nameEn: "Vasil Terziev",
    affiliationBg: "Кмет на Столична община",
    affiliationEn: "Mayor of Sofia Municipality",
    status: "to_be_confirmed",
  },
  {
    id: "speaker-tanya-chuntova",
    nameBg: "Таня Чунтова",
    nameEn: "",
    affiliationBg: "Бюро за връзка на Европейския парламент в България",
    affiliationEn: null,
  },
  {
    id: "speaker-pete-forger",
    nameBg: "Пит Форгер",
    nameEn: "Pete Forger",
    affiliationBg:
      "Консултант към борда на ENCC и директор „Култура“ на град Льовен, понастоящем ръководещ кандидатурата на Льовен за Европейска столица на културата 2030",
    affiliationEn:
      "Consultant to the ENCC board and Director of Culture of the City of Leuven, currently leading Leuven’s bid for European Capital of Culture 2030",
  },
  {
    id: "speaker-yuriy-valkovsky",
    nameBg: "Юрий Вълковски",
    nameEn: "Yuri Valkovski",
    affiliationBg: "Изпълнителен директор, Фондация „Народни читалища“",
    affiliationEn: "Executive Director, “Narodni Chitalishta” Foundation",
  },
  {
    id: "speaker-katarzyna-pongowska",
    nameBg: "Катажина Понговска",
    nameEn: "Katarzyna Pongowska",
    affiliationBg:
      "Заместник-директор по програмни въпроси, Регионален център за развитие на културата (WOAK), Полша",
    affiliationEn:
      "Deputy Director for Programme Affairs, Regional Center for Cultural Development (WOAK), Poland",
  },
  {
    id: "speaker-irina-dakova",
    nameBg: "Ирина Дакова",
    nameEn: "Irina Dakova",
    affiliationBg: "Заместник-кмет по култура и туризъм, Столична община",
    affiliationEn: "Deputy Mayor for Culture and Tourism, Sofia Municipality",
  },
  {
    id: "speaker-silvana-suleyman",
    nameBg: "Силвана Сюлейман",
    nameEn: "Silvana Suleyman",
    affiliationBg: "Директор на Видински фонд „Читалища“",
    affiliationEn: "Director, Vidin “Community Centers” Foundation",
  },
  {
    id: "speaker-neli-roydeva",
    nameBg: "Нели Ройдева",
    nameEn: "Neli Roydeva",
    affiliationBg:
      "Председател, Сдружение „Читалища с бъдеще – 2012“, община Тунджа",
    affiliationEn:
      "Chair, “Community Centers with a Future – 2012” Association, Tundzha Municipality",
  },
  {
    id: "speaker-donka-mihaylova",
    nameBg: "Донка Михайлова",
    nameEn: "Donka Mihaylova",
    affiliationBg: "Кмет на община Троян",
    affiliationEn: "Mayor of Troyan Municipality",
  },
  {
    id: "speaker-teodora-dacheva",
    nameBg: "Теодора Дачева",
    nameEn: "Teodora Dacheva",
    affiliationBg: "Заместник изпълнителен директор на НСОРБ",
    affiliationEn:
      "Deputy Executive Director of the National Association of Municipalities in the Republic of Bulgaria (NAMRB)",
  },
  {
    id: "speaker-srebra-kaseva",
    nameBg: "Сребра Касева",
    nameEn: "",
    affiliationBg: "Заместник-кмет на община Казанлък",
    affiliationEn: null,
  },
  {
    id: "speaker-albena-nedeva",
    nameBg: "Албена Недева",
    nameEn: "",
    affiliationBg: "Председател на Общински читалищен съвет Търговище",
    affiliationEn: null,
  },
  {
    id: "speaker-lilyana-barganska",
    nameBg: "Лиляна Барганска",
    nameEn: "",
    affiliationBg:
      "Председател на Народно читалище „Васил Левски – 1945“, Варна",
    affiliationEn: null,
  },
  {
    id: "speaker-else-kristensen-redzepovic",
    nameBg: "Елзе Кристенсен-Реджепович",
    nameEn: "",
    affiliationBg:
      "Бивш член на Панела за подбор и мониторинг на Европейска столица на културата, номинирана от Европейския парламент",
    affiliationEn: null,
  },
  {
    id: "speaker-ruska-boyadzhieva",
    nameBg: "Руска Бояджиева",
    nameEn: "",
    affiliationBg: "Изпълнителен директор на Фондация „Бургас 2032“",
    affiliationEn: null,
  },
  {
    id: "speaker-gabrovo-representative",
    nameBg: "Представител на община Габрово",
    nameEn: "",
    affiliationBg: null,
    affiliationEn: null,
  },
  {
    id: "speaker-tsveta-nenova",
    nameBg: "Цвета Ненова",
    nameEn: "",
    affiliationBg: "Експерт, Русе",
    affiliationEn: null,
  },
  {
    id: "speaker-orlin-denkov",
    nameBg: "Орлин Денков",
    nameEn: "",
    affiliationBg: "Председател на Народно читалище „Иван Вазов – 2014“, София",
    affiliationEn: null,
  },
  {
    id: "speaker-mep-tbc",
    nameBg: "Член на Европейския парламент",
    nameEn: "",
    affiliationBg: null,
    affiliationEn: null,
    status: "to_be_confirmed",
  },
  {
    id: "speaker-piotr-michalowski",
    nameBg: "Пьотр Михаловски",
    nameEn: "",
    affiliationBg:
      "Член на борда на Европейската мрежа на културните центрове (ENCC), координатор на Общностната група на ENCC за култура и творчество в селските райони, експерт по териториално развитие и сътрудничество град–село",
    affiliationEn: null,
  },
  {
    id: "speaker-deputy-minister-rusev",
    nameBg: "Заместник-министър Русев",
    nameEn: "",
    affiliationBg: "Министерство на труда и социалната политика",
    affiliationEn: null,
  },
  {
    id: "speaker-deputy-minister-chakarov",
    nameBg: "Заместник-министър Чакъров",
    nameEn: "",
    affiliationBg: "Министерство на земеделието и храните",
    affiliationEn: null,
  },
  {
    id: "speaker-elena-ivanova",
    nameBg: "Елена Иванова",
    nameEn: "",
    affiliationBg:
      "Директор, Дирекция „Развитие на селските райони“, Министерство на земеделието и храните",
    affiliationEn: null,
  },
  {
    id: "speaker-tsvetelina-penkova",
    nameBg: "Цветелина Пенкова",
    nameEn: "",
    affiliationBg:
      "Член на Европейския парламент, заместник-председател, Комисия по промишленост, изследвания и енергетика",
    affiliationEn: null,
  },
  {
    id: "speaker-iliya-godev",
    nameBg: "Илия Годев",
    nameEn: "",
    affiliationBg:
      "Секретар на Народно читалище „Проф. д-р Асен Златаров – 1927“, с. Смилян, област Смолян",
    affiliationEn: null,
  },
  {
    id: "speaker-anton-kutev",
    nameBg: "Антон Кутев",
    nameEn: "",
    affiliationBg:
      "Председател на Комисията по културата и медиите, Народно събрание на Република България",
    affiliationEn: null,
  },
];

export type ScheduleItemSeed = {
  id: string;
  dayId: string;
  panelId: string | null;
  startTime: string | null;
  endTime: string | null;
  itemType: ScheduleItemType;
  titleBg: string;
  titleEn: string;
  descriptionBg: string | null;
  descriptionEn: string | null;
  status: ScheduleItemStatus;
  sortOrder: number;
  visible: boolean;
  speakerIds: string[];
};

export const scheduleItemSeeds: ScheduleItemSeed[] = [
  {
    id: "item-registration",
    dayId: "day-2026-09-18",
    panelId: null,
    startTime: "09:00",
    endTime: "09:30",
    itemType: "registration",
    titleBg: "Регистрация и кафе",
    titleEn: "Registration and coffee",
    descriptionBg: null,
    descriptionEn: null,
    status: "confirmed",
    sortOrder: 0,
    visible: true,
    speakerIds: [],
  },
  {
    id: "item-opening",
    dayId: "day-2026-09-18",
    panelId: null,
    startTime: "09:30",
    endTime: "09:50",
    itemType: "opening",
    titleBg: "Официално откриване",
    titleEn: "Official opening",
    descriptionBg: "Приветствени думи",
    descriptionEn: "Opening remarks",
    status: "confirmed",
    sortOrder: 10,
    visible: true,
    speakerIds: [
      "speaker-evtim-miloshev",
      "speaker-vasil-terziev",
      "speaker-tanya-chuntova",
      "speaker-pete-forger",
      "speaker-yuriy-valkovsky",
    ],
  },
  {
    id: "item-panel-1-opening",
    dayId: "day-2026-09-18",
    panelId: "panel-1-local-dialogue",
    startTime: "09:50",
    endTime: "10:05",
    itemType: "opening",
    titleBg: "Встъпителни думи",
    titleEn: "Opening Remarks",
    descriptionBg: null,
    descriptionEn: null,
    status: "confirmed",
    sortOrder: 20,
    visible: true,
    speakerIds: ["speaker-katarzyna-pongowska"],
  },
  {
    id: "item-active-chitalishta",
    dayId: "day-2026-09-18",
    panelId: "panel-1-local-dialogue",
    startTime: "10:05",
    endTime: "10:15",
    itemType: "talk",
    titleBg: "Представяне на програма „Активни читалища“",
    titleEn: "Presentation of the “Active Community Centers” Program",
    descriptionBg: null,
    descriptionEn: null,
    status: "confirmed",
    sortOrder: 30,
    visible: true,
    speakerIds: ["speaker-irina-dakova"],
  },
  {
    id: "item-roundtable-1",
    dayId: "day-2026-09-18",
    panelId: "panel-1-local-dialogue",
    startTime: "10:15",
    endTime: "11:15",
    itemType: "roundtable",
    titleBg:
      "Кръгла маса (Част 1): Отношенията между читалищата/културните центрове и общините — добри практики и предизвикателства",
    titleEn:
      "Roundtable (Part 1): Relations between community centers/cultural centers and municipalities—best practices and challenges",
    descriptionBg:
      "Последвано от въпроси и коментари от читалищни и общински представители в публиката.",
    descriptionEn:
      "Followed by questions and comments from community center and municipal representatives in the audience.",
    status: "confirmed",
    sortOrder: 40,
    visible: true,
    speakerIds: [
      "speaker-silvana-suleyman",
      "speaker-neli-roydeva",
      "speaker-donka-mihaylova",
      "speaker-teodora-dacheva",
    ],
  },
  {
    id: "item-break-1",
    dayId: "day-2026-09-18",
    panelId: "panel-1-local-dialogue",
    startTime: "11:15",
    endTime: "11:30",
    itemType: "break",
    titleBg: "Кафе-пауза",
    titleEn: "Coffee break",
    descriptionBg: null,
    descriptionEn: null,
    status: "confirmed",
    sortOrder: 50,
    visible: true,
    speakerIds: [],
  },
  {
    id: "item-roundtable-2",
    dayId: "day-2026-09-18",
    panelId: "panel-1-local-dialogue",
    startTime: "11:30",
    endTime: "12:15",
    itemType: "roundtable",
    titleBg:
      "Кръгла маса (Част 2): Отношенията между читалищата/културните центрове и общините — добри практики и предизвикателства",
    titleEn:
      "Roundtable (Part 2): Relations between community centers/cultural centers and municipalities—best practices and challenges",
    descriptionBg:
      "Последвано от въпроси и коментари от читалищни и общински представители в публиката.",
    descriptionEn:
      "Followed by questions and comments from community center and municipal representatives in the audience.",
    status: "confirmed",
    sortOrder: 60,
    visible: true,
    speakerIds: [
      "speaker-srebra-kaseva",
      "speaker-albena-nedeva",
      "speaker-lilyana-barganska",
    ],
  },
  {
    id: "item-lunch-1",
    dayId: "day-2026-09-18",
    panelId: "panel-1-local-dialogue",
    startTime: "12:15",
    endTime: "13:00",
    itemType: "lunch",
    titleBg: "Обяд",
    titleEn: "",
    descriptionBg: null,
    descriptionEn: null,
    status: "confirmed",
    sortOrder: 70,
    visible: true,
    speakerIds: [],
  },
  {
    id: "item-heart-of-chitalishte",
    dayId: "day-2026-09-18",
    panelId: "panel-2-european-capital",
    startTime: "13:00",
    endTime: "13:15",
    itemType: "talk",
    titleBg: "„Сърцето на читалището“",
    titleEn: "",
    descriptionBg:
      "Документално видео за Народно читалище „Николай Хайтов - 1936“, София",
    descriptionEn: null,
    status: "confirmed",
    sortOrder: 80,
    visible: true,
    speakerIds: [],
  },
  {
    id: "item-panel-2-keynote",
    dayId: "day-2026-09-18",
    panelId: "panel-2-european-capital",
    startTime: "13:15",
    endTime: "13:45",
    itemType: "talk",
    titleBg: "Основен доклад „ЕСК като предизвикателство и възможност!“",
    titleEn: "",
    descriptionBg: null,
    descriptionEn: null,
    status: "confirmed",
    sortOrder: 90,
    visible: true,
    speakerIds: ["speaker-else-kristensen-redzepovic"],
  },
  {
    id: "item-capital-presentations",
    dayId: "day-2026-09-18",
    panelId: "panel-2-european-capital",
    startTime: "13:45",
    endTime: "14:15",
    itemType: "talk",
    titleBg: "По пътя към титлата Европейска столица на културата",
    titleEn: "",
    descriptionBg: null,
    descriptionEn: null,
    status: "confirmed",
    sortOrder: 100,
    visible: true,
    speakerIds: [
      "speaker-ruska-boyadzhieva",
      "speaker-gabrovo-representative",
    ],
  },
  {
    id: "item-capital-dialogue",
    dayId: "day-2026-09-18",
    panelId: "panel-2-european-capital",
    startTime: "14:15",
    endTime: "15:15",
    itemType: "discussion",
    titleBg: "Диалог",
    titleEn: "",
    descriptionBg:
      "Размисли по чутите представяния и очакванията към бъдещата българска Европейска столица на културата",
    descriptionEn: null,
    status: "confirmed",
    sortOrder: 110,
    visible: true,
    speakerIds: [
      "speaker-pete-forger",
      "speaker-tsveta-nenova",
      "speaker-orlin-denkov",
      "speaker-mep-tbc",
    ],
  },
  {
    id: "item-audience-dialogue",
    dayId: "day-2026-09-18",
    panelId: "panel-2-european-capital",
    startTime: "15:15",
    endTime: "15:30",
    itemType: "discussion",
    titleBg: "Диалог с публиката",
    titleEn: "",
    descriptionBg: null,
    descriptionEn: null,
    status: "confirmed",
    sortOrder: 120,
    visible: true,
    speakerIds: [],
  },
  {
    id: "item-break-2",
    dayId: "day-2026-09-18",
    panelId: null,
    startTime: "15:30",
    endTime: "15:45",
    itemType: "break",
    titleBg: "Кафе-пауза",
    titleEn: "Coffee break",
    descriptionBg: null,
    descriptionEn: null,
    status: "confirmed",
    sortOrder: 130,
    visible: true,
    speakerIds: [],
  },
  {
    id: "item-panel-3-opening",
    dayId: "day-2026-09-18",
    panelId: "panel-3-regional-development",
    startTime: "15:45",
    endTime: "16:00",
    itemType: "opening",
    titleBg: "Встъпителни думи",
    titleEn: "",
    descriptionBg: null,
    descriptionEn: null,
    status: "confirmed",
    sortOrder: 140,
    visible: true,
    speakerIds: ["speaker-piotr-michalowski"],
  },
  {
    id: "item-regional-panel",
    dayId: "day-2026-09-18",
    panelId: "panel-3-regional-development",
    startTime: "16:00",
    endTime: "17:00",
    itemType: "panel",
    titleBg: "Панелна дискусия",
    titleEn: "",
    descriptionBg: null,
    descriptionEn: null,
    status: "confirmed",
    sortOrder: 150,
    visible: true,
    speakerIds: [
      "speaker-deputy-minister-rusev",
      "speaker-deputy-minister-chakarov",
      "speaker-elena-ivanova",
      "speaker-tsvetelina-penkova",
      "speaker-iliya-godev",
    ],
  },
  {
    id: "item-anton-kutev-comment",
    dayId: "day-2026-09-18",
    panelId: "panel-3-regional-development",
    startTime: "17:00",
    endTime: "17:15",
    itemType: "talk",
    titleBg: "Коментар върху дискусията и изказване по темата",
    titleEn: "",
    descriptionBg: null,
    descriptionEn: null,
    status: "confirmed",
    sortOrder: 160,
    visible: true,
    speakerIds: ["speaker-anton-kutev"],
  },
  {
    id: "item-audience-discussion",
    dayId: "day-2026-09-18",
    panelId: "panel-3-regional-development",
    startTime: "17:15",
    endTime: "17:45",
    itemType: "discussion",
    titleBg: "Дискусия с публиката",
    titleEn: "",
    descriptionBg: null,
    descriptionEn: null,
    status: "confirmed",
    sortOrder: 170,
    visible: true,
    speakerIds: [],
  },
  {
    id: "item-closing",
    dayId: "day-2026-09-18",
    panelId: null,
    startTime: "17:45",
    endTime: "18:00",
    itemType: "closing",
    titleBg: "Заключение и препоръки",
    titleEn: "",
    descriptionBg: null,
    descriptionEn: null,
    status: "confirmed",
    sortOrder: 180,
    visible: true,
    speakerIds: [],
  },
  {
    id: "item-day-2-visits",
    dayId: "day-2026-09-19",
    panelId: null,
    startTime: null,
    endTime: null,
    itemType: "visit",
    titleBg: "Посещения на две читалища в София и околността",
    titleEn: "",
    descriptionBg: "Сутрин.",
    descriptionEn: null,
    status: "confirmed",
    sortOrder: 0,
    visible: true,
    speakerIds: [],
  },
];
